const express = require('express')
const app = express()

const port = process.env.PORT || 3000

app.set("view engine", "ejs")
app.set('views', __dirname + '/views')
app.use(express.static(__dirname + '/public'))

//Web Path



app.get("/", (req , res) => {
    console.log("Ready")
    res.render('index')
}) 

app.get("/home", (req , res) => {
    res.render("home", {titleService: "Message of home"})
})

app.get('/help', (req, res) => {
    res.render('help');
  })

  app.get('/about', (req, res) => {
    res.render('about');
  })

  app.get('/contact', (req, res) => {
    res.render('contact');
  })

app.get("/services", (req , res) => {
    res.render("service", {titleService: "Message of service"})
})


app.use((req, res, next) => {
    res.status(404).render('404', {
        TitleError: "An unexpected 404 error occurred",
        DescriptionError: "The error was generated by..."
    })
})

app.listen(port, () => {
    console.log("Server in ready in" ,port)
})

const userRouter = require('./router/web_path')